# Generated by Django 4.2.5 on 2023-09-21 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imovel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma_nome', models.CharField(max_length=255, verbose_name='Nome da Plataforma')),
                ('plataforma_taxa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taxa da Plataforma')),
                ('data_hora_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora de Criação')),
                ('data_hora_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data e Hora da Última Atualização')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imovel.imovel', verbose_name='Imóvel')),
            ],
        ),
    ]
