# Generated by Django 4.2.5 on 2023-09-22 21:26

from django.db import migrations

class Migration(migrations.Migration):
    def create_anuncio(apps, schema_editor):
        """Cria 3 anúncios"""
        Imovel = apps.get_model("imovel", "Imovel")
        imoveis = Imovel.objects.all()
        Anuncio = apps.get_model("anuncio", "Anuncio")
        db_alias = schema_editor.connection.alias
        Anuncio.objects.using(db_alias).bulk_create(
            [
                Anuncio(imovel=imoveis[0], plataforma_nome="AirBnB", plataforma_taxa=0.10),
                Anuncio(imovel=imoveis[1], plataforma_nome="Booking", plataforma_taxa=0.15),
                Anuncio(imovel=imoveis[2], plataforma_nome="TripAdvisor", plataforma_taxa=0.20),
            ]
        )

    dependencies = [
        ('anuncio', '0001_initial'),
        ('imovel', '0002_create_imovel')
    ]

    operations = [
        migrations.RunPython(create_anuncio)
    ]
