# Generated by Django 4.2.5 on 2023-09-21 19:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anuncio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Código da Reserva')),
                ('check_in', models.DateField(verbose_name='Data de Check-in')),
                ('check_out', models.DateField(verbose_name='Data de Check-out')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Total')),
                ('comentario', models.TextField(verbose_name='Comentário')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncio.anuncio', verbose_name='Anúncio')),
            ],
        ),
    ]
