# Generated by Django 4.2.5 on 2023-09-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('codigo', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Código do Imóvel')),
                ('limite', models.IntegerField(verbose_name='Limite de Hóspedes')),
                ('qntd_banheiro', models.IntegerField(verbose_name='Quantidade de banheiros')),
                ('animais', models.BooleanField(default=False, verbose_name='Permissão para Animais de Estimação')),
                ('valor_limpeza', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor para Limpeza')),
                ('data_ativacao', models.DateField(verbose_name='Data de Ativação')),
                ('data_hora_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora de Criação')),
                ('data_hora_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data e Hora da Última Atualização')),
            ],
        ),
    ]
