# Generated by Django 4.2.5 on 2023-09-22 21:27

from django.db import migrations

class Migration(migrations.Migration):
    def create_imovel(apps, schema_editor):
        """Cria 5 imóveis"""
        Imovel = apps.get_model("imovel", "Imovel")
        db_alias = schema_editor.connection.alias
        Imovel.objects.using(db_alias).bulk_create(
            [
                Imovel(
                    limite=3,
                    qntd_banheiro=2,
                    animais=True,
                    valor_limpeza=150.00,
                    data_ativacao='2023-04-15',
                ),
                Imovel(
                    limite=4,
                    qntd_banheiro=1,
                    animais=False,
                    valor_limpeza=170.50,
                    data_ativacao='2023-06-25',
                ),
                Imovel(
                    limite=1,
                    qntd_banheiro=1,
                    animais=False,
                    valor_limpeza=50.00,
                    data_ativacao='2023-03-20',
                ),
                Imovel(
                    limite=8,
                    qntd_banheiro=3,
                    animais=True,
                    valor_limpeza=300.00,
                    data_ativacao='2023-09-15',
                ),
                Imovel(
                    limite=3,
                    qntd_banheiro=1,
                    animais=False,
                    valor_limpeza=120.00,
                    data_ativacao='2023-09-21',
                ),
            ]
        )

    dependencies = [
        ('imovel', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_imovel)
    ]
